#! /usr/bin/env python3

import os

from pygrist_mini import GristClient


def create_av_request(grist: GristClient) -> int:
    for case in grist.sql("select * from Cases where Hearing_start is not null"):
        grist.add_records("Case_events",
                    [{
                        "Case": case["id"],
                        "Timestamp": case["Hearing_start"],
                        "Event": "Hearing",
                        "Note": case["Hearing_Location"],
                    }])

    return 0


def main():
    from argparse import ArgumentParser
    parser = ArgumentParser()

    parser.add_argument(
                        "--grist-root-url", metavar="URL",
                        required=True)
    parser.add_argument(
                        "--grist-doc-id", metavar="DOC_ID",
                        required=True)
    parser.add_argument(
                        "--grist-api-key", metavar="FILENAME",
                        default=os.path.expanduser("~/.grist-api-key"),
                        required=True)

    args = parser.parse_args()
    with open(args.grist_api_key) as inf:
        grist_api_key = inf.read().strip()

    grist_client = GristClient(args.grist_root_url, grist_api_key, args.grist_doc_id)

    import sys
    sys.exit(create_av_request(grist_client))


if __name__ == "__main__":
    main()
