#!/usr/bin/env -S uv run --script
# requires-python = ">=3.13"
# /// script
# dependencies = [
#   "pygrist-mini",
#   "typed-argparse",
# ]
# ///

import datetime
import os
from collections import defaultdict
from collections.abc import Collection, Mapping, Sequence
from dataclasses import dataclass
from enum import IntEnum, StrEnum
from typing import TypeVar, cast

import typed_argparse as tap
from pygrist_mini import GristClient


class CommonArgs(tap.TypedArgs):
    grist_root_url: str = tap.arg(metavar="URL")
    grist_doc_id: str = tap.arg(metavar="DOC_ID")
    grist_api_key: str = tap.arg(
                    metavar="FILENAME",
                    default=os.path.expanduser("~/.grist-api-key"))


def get_grist_client(args: CommonArgs) -> GristClient:
    with open(args.grist_api_key) as inf:
        grist_api_key = inf.read().strip()

    return GristClient(args.grist_root_url, grist_api_key, args.grist_doc_id)


class FindArgs(CommonArgs):
    request_group_id: int = tap.arg(positional=True)
    timezone: str | None = tap.arg(default=None)
    case: int | None = tap.arg(default=None)
    without_appellant: bool = tap.arg(default=False)
    without_instructor: bool = tap.arg(default=False)


class AvCategory(StrEnum):
    committee = "committee"
    core = "core"


class PersonCategory(StrEnum):
    chair = "Committee Chair"
    student_ugrad = "Student (undergrad)"
    student_grad = "Student (graduate)"
    faculty = "Faculty"
    faculty_emerg = "Faculty for Emergencies"
    committee = "Faculty on Committee"
    committee_leave = "Faculty on Committee on Leave"
    other = "Other"


@dataclass(frozen=True)
class Timespan:
    start: datetime.datetime
    end: datetime.datetime


IdentifierT = TypeVar("IdentifierT")


@dataclass(frozen=True)
class Overlap[IdentifierT]:
    span: Timespan
    counts: Mapping[IdentifierT, int]


class TimeType(IntEnum):
    # This ensures that ends sort before starts, so that we don't get
    # 'fake' overlaps when ends coincide with starts.
    end = 0
    start = 1


def timespans_to_overlaps[IdentifierT](
            ids_and_spans: Sequence[tuple[IdentifierT, Timespan]]
        ) -> Sequence[Overlap[IdentifierT]]:
    all_spans = sorted(
        [(time, what, identifier)
            for identifier, span in ids_and_spans
            for what, time in [(TimeType.start, span.start), (TimeType.end, span.end)]
        ],
    )

    result: list[Overlap[IdentifierT]] = []
    cur_counts: dict[IdentifierT, int] = {}
    last_time = None

    for time, what, identifier in all_spans:
        if last_time is not None:
            if last_time != time:
                result.append(
                    Overlap(
                            Timespan(start=last_time, end=time),
                            counts=cur_counts.copy())
                )
        cur_counts[identifier] = (
            cur_counts.get(identifier, 0)
                + (1 if what == TimeType.start else -1))
        if cur_counts[identifier] == 0:
            del cur_counts[identifier]

        last_time = time

    assert not cur_counts

    return result


@dataclass(frozen=True)
class Case:
    id: int
    fair_id: int
    appellants: Sequence[int]
    instructors: Sequence[int]


def get_case_participants(grist: GristClient, case_id: int, role: str) -> list[int]:
    return [row["Person"]
        for row in grist.sql(
            "select Person from Case_participants "
            f'where "Case" = {case_id} '
            f"and Role = '{role}'"
        )]


def av_category_counts(counts: Mapping[int, int], core_persons: Collection[int]):
    cat_counts: defaultdict[AvCategory, int] = defaultdict(int)
    for p, cnt in counts.items():
        cat = AvCategory.core if p in core_persons else AvCategory.committee
        cat_counts[cat] = cat_counts.get(cat, 0) + cnt
    return cat_counts


K = TypeVar("K")


def min_counts(a: Mapping[K, int], b: Mapping[K, int]):
    result: dict[K, int] = {}
    for k, a_cnt in a.items():
        cnt = min(a_cnt, b.get(k, 0))
        if cnt:
            result[k] = cnt
    return result


def min_counts_until[IdentifierT](
            overlaps: Sequence[Overlap[IdentifierT]],
            i: int,
            until: datetime.datetime) -> Mapping[IdentifierT, int]:
    ov = overlaps[i]
    cur_span_end = ov.span.end
    min_id_counts = ov.counts
    forward_i = i + 1
    valid = False
    while forward_i < len(overlaps):
        forward_ov = overlaps[forward_i]
        if forward_ov.span.start != cur_span_end:
            # no contiguous block until 'until'
            break

        min_id_counts = min_counts(
            min_id_counts,
            forward_ov.counts,
        )
        cur_span_end = forward_ov.span.end
        if cur_span_end >= until:
            valid = True
            break

        forward_i += 1
        if forward_i >= len(overlaps):
            break

    if valid:
        return min_id_counts
    else:
        return {}


def find_slots(args: FindArgs):
    grist = get_grist_client(args)

    availabilities: list[tuple[int, Timespan]] = [
            (row["Person"], Timespan(
                    start=datetime.datetime.fromtimestamp(row["Start"]),
                    end=datetime.datetime.fromtimestamp(row["End"]),
                )
        )
        for row in grist.sql(
                "select Person, Person_category, Start, End "
                "from Availability "
                f"where Available = 1 and Request_group = {args.request_group_id}")
        ]
    person_to_category = {
        cast(int, row["id"]): PersonCategory(row["Category"])
        for row in grist.sql(
                "select id, Category "
                "from Persons")
    }
    person_to_netid = {
        cast(int, row["id"]): cast("str", row["NetID"])
        for row in grist.sql(
                "select id, NetID "
                "from Persons")
    }
    cases_with_need = [
            Case(
                 id=row["id"],
                 fair_id=int(row["CaseID"]),
                 appellants=get_case_participants(
                                    grist, row["id"], "Appellant"),
                 instructors=get_case_participants(
                                    grist, row["id"], "Instructor"),

             )
            for row in grist.sql(
                "select id, CaseID from Cases where substr(State, 1, 1) = '5'")]

    committee_spans = [
        (person, span) for person, span in availabilities
        if person_to_category[person] == PersonCategory.committee
    ]
    for case in cases_with_need:
        if args.case is not None and args.case != case.fair_id:
            continue

        core_persons: list[int] = []
        if not args.without_appellant:
            core_persons = [*core_persons, *case.appellants]
        if not args.without_instructor:
            core_persons = [*core_persons, *case.instructors]

        overlaps = timespans_to_overlaps([
            *[(person, span)
                for person, span in availabilities
                if person in core_persons],
            *[(person, span)
                for person, span in committee_spans
                if person not in core_persons],
        ],)

        print(f"Case {case.fair_id}:")

        for i, ov in enumerate(overlaps):
            assert all(cnt == 1 for cnt in ov.counts.values())

            cat_counts = av_category_counts(ov.counts, core_persons)

            if (cat_counts[AvCategory.committee] >= 3
                        and cat_counts[AvCategory.core] >= len(core_persons)):
                min_person_counts_open = min_counts_until(
                        overlaps, i, ov.span.start + datetime.timedelta(minutes=60))
                min_person_counts_closed = min_counts_until(
                        overlaps, i, ov.span.start + datetime.timedelta(minutes=90))

                min_cat_counts_open = av_category_counts(
                        min_person_counts_open, core_persons)
                min_cat_counts_closed = av_category_counts(
                        min_person_counts_closed, core_persons)

                if (min_cat_counts_closed[AvCategory.committee] >= 3
                        and min_cat_counts_open[AvCategory.core] >= len(core_persons)):
                    committee_netids = sorted([
                        person_to_netid[p]
                        for p in min_person_counts_closed if p not in core_persons])
                    print(f"    {ov.span.start}: {', '.join(committee_netids)}")


def main():
    tap.Parser(
        FindArgs
        ).bind(find_slots).run()


if __name__ == "__main__":
    main()
